/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    categories: Category;
    'blog-subscribers': BlogSubscriber;
    services: Service;
    equipment: Equipment;
    'equipment-requests': EquipmentRequest;
    'equipment-usage': EquipmentUsage;
    'inventory-items': InventoryItem;
    'team-members': TeamMember;
    projects: Project;
    events: Event;
    'event-registrations': EventRegistration;
    'event-attendance': EventAttendance;
    resources: Resource;
    gallery: Gallery;
    faqs: Faq;
    testimonials: Testimonial;
    'contact-messages': ContactMessage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'blog-subscribers': BlogSubscribersSelect<false> | BlogSubscribersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    equipment: EquipmentSelect<false> | EquipmentSelect<true>;
    'equipment-requests': EquipmentRequestsSelect<false> | EquipmentRequestsSelect<true>;
    'equipment-usage': EquipmentUsageSelect<false> | EquipmentUsageSelect<true>;
    'inventory-items': InventoryItemsSelect<false> | InventoryItemsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    'event-attendance': EventAttendanceSelect<false> | EventAttendanceSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'landing-config': LandingConfig;
    'equipo-page': EquipoPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'landing-config': LandingConfigSelect<false> | LandingConfigSelect<true>;
    'equipo-page': EquipoPageSelect<false> | EquipoPageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  avatar?: (number | null) | Media;
  /**
   * Posición X Y en porcentaje (ej: "50% 30%")
   */
  imagePosition?: string | null;
  bio?: string | null;
  /**
   * Ej: Ingeniero Electrónico, Diseñador 3D
   */
  jobTitle?: string | null;
  showInTeam?: boolean | null;
  category?: ('leadership' | 'specialist' | 'collaborator') | null;
  experience?: string | null;
  educationStatus?: ('graduated' | 'studying' | 'titled' | 'bachelor' | 'masters' | 'doctorate') | null;
  achievements?:
    | {
        achievement?: string | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  linkedin?: string | null;
  github?: string | null;
  role: 'admin' | 'editor' | 'author' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descripción de la imagen para accesibilidad y SEO
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    techBox?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    gallery?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL amigable (formato: YYYY/MM/slug)
   */
  slug?: string | null;
  /**
   * Resumen corto para listados y SEO
   */
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | User;
  categories?: (number | Category)[] | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  views?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Separadas por comas
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL amigable (se genera automáticamente)
   */
  slug?: string | null;
  description?: string | null;
  parent?: (number | null) | Category;
  /**
   * Nombre del icono de Lucide (ej: "Cpu", "Printer")
   */
  icon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-subscribers".
 */
export interface BlogSubscriber {
  id: number;
  email: string;
  /**
   * Desmarcar para dejar de enviar correos a este suscriptor
   */
  active?: boolean | null;
  unsubscribeToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestiona los servicios que ofrece el FabLab
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * Se genera automáticamente del nombre
   */
  slug: string;
  category: '3d-printing' | 'laser-cutting' | 'cnc' | 'electronics' | 'design' | 'training';
  /**
   * Resumen breve para tarjetas y listados
   */
  description: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Nombre del icono de Lucide (ej: "Printer", "Cpu", "Scissors")
   */
  icon?: string | null;
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tabla de precios del servicio
   */
  pricing?:
    | {
        item: string;
        /**
         * Ej: "$5.000/hora", "Consultar", "Gratis para miembros"
         */
        price: string;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  featured?: boolean | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestiona las máquinas y herramientas del FabLab
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment".
 */
export interface Equipment {
  id: number;
  name: string;
  slug: string;
  category: '3d-printer' | 'laser-cutter' | 'cnc' | 'electronics' | 'hand-tools' | '3d-scanner' | 'other';
  brand?: string | null;
  model?: string | null;
  description: string;
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  materials?:
    | {
        material: string;
        id?: string | null;
      }[]
    | null;
  manuals?:
    | {
        title: string;
        file?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('available' | 'maintenance' | 'out-of-service') | null;
  /**
   * Ej: "Sala 1", "Taller Principal"
   */
  location?: string | null;
  requiresTraining?: boolean | null;
  /**
   * Si está activado, el equipo será visible en la página /tecnologías
   */
  showInTecnologias?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Solicitudes de nuevos equipos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-requests".
 */
export interface EquipmentRequest {
  id: number;
  equipmentName: string;
  description?: string | null;
  quantity: number;
  justification: string;
  status: 'pending' | 'approved' | 'rejected';
  requestedBy?: (number | null) | User;
  reviewedBy?: (number | null) | User;
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Historial de uso de equipos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-usage".
 */
export interface EquipmentUsage {
  id: number;
  equipmentId: string;
  equipmentName: string;
  user: number | User;
  /**
   * Nombre del usuario al momento del uso (para historial)
   */
  userName?: string | null;
  startTime: string;
  endTime?: string | null;
  estimatedDuration: '30min' | '1h' | '2h' | '4h' | '8h' | '1d' | '2d' | '1w';
  description?: string | null;
  status: 'active' | 'completed';
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestiona el inventario interno (consumibles, materiales, componentes)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-items".
 */
export interface InventoryItem {
  id: number;
  name: string;
  /**
   * Código interno del artículo
   */
  sku?: string | null;
  category: 'consumable' | 'material' | 'component' | 'tool' | 'supply' | 'other';
  description?: string | null;
  image?: (number | null) | Media;
  quantity: number;
  unit?: ('unit' | 'kg' | 'g' | 'm' | 'cm' | 'l' | 'ml' | 'roll' | 'sheet' | 'pack') | null;
  /**
   * Cantidad mínima antes de alertar
   */
  minimumStock?: number | null;
  /**
   * Ej: "Bodega A", "Estante 3"
   */
  location?: string | null;
  supplier?: string | null;
  unitCost?: number | null;
  status?: ('available' | 'low-stock' | 'out-of-stock') | null;
  /**
   * Notas internas sobre este artículo
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  category: 'leadership' | 'specialist' | 'collaborator';
  specialty?: string | null;
  image: number | Media;
  bio?: string | null;
  experience?: string | null;
  achievements?:
    | {
        achievement?: string | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    email?: string | null;
    linkedin?: string | null;
    github?: string | null;
    twitter?: string | null;
  };
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  category: 'Hardware' | 'Software' | 'Diseño' | 'IoT';
  description: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Herramientas, lenguajes, materiales utilizados
   */
  technologies?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Miembros del equipo o colaboradores externos
   */
  creators?:
    | {
        /**
         * Selecciona un usuario registrado
         */
        teamMember?: (number | null) | User;
        externalName?: string | null;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Repositorio, video, documentación, etc.
   */
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Activar datos de horas de práctica
   */
  practiceHoursEnabled?: boolean | null;
  /**
   * Información confidencial de horas de práctica (no visible al público)
   */
  practiceHours?: {
    beneficiaryType?: string | null;
    institutionName?: string | null;
    institutionRut?: string | null;
    email?: string | null;
    phone?: string | null;
    commune?: string | null;
    referringOrganization?: string | null;
    /**
     * Datos de cada especialista asociado
     */
    specialists?:
      | {
          firstName: string;
          paternalLastName: string;
          maternalLastName?: string | null;
          rut: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Datos de beneficiarios para plantilla de bidirección
     */
    bidireccionEntries?:
      | {
          tipoBeneficiario: string;
          rut: string;
          firstName: string;
          paternalLastName: string;
          maternalLastName?: string | null;
          rol: string;
          horasDocente?: number | null;
          horasEstudiante?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  year?: number | null;
  featured?: boolean | null;
  status?: ('draft' | 'published') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestiona talleres, cursos y eventos del FabLab
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  type: 'workshop' | 'course' | 'talk' | 'hackathon' | 'open-day' | 'meetup';
  description: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  startDate: string;
  endDate?: string | null;
  /**
   * Ej: "FabLab INACAP Sede Los Ángeles" o "Online"
   */
  location?: string | null;
  isOnline?: boolean | null;
  instructor?: (number | null) | User;
  /**
   * Usar si el instructor no es miembro del equipo
   */
  externalInstructor?: string | null;
  /**
   * Número máximo de participantes (0 = ilimitado)
   */
  capacity?: number | null;
  /**
   * Link a Google Forms, Eventbrite, etc.
   */
  registrationUrl?: string | null;
  /**
   * Ej: "Gratis", "$10.000", "Gratis para miembros"
   */
  price?: string | null;
  requirements?:
    | {
        requirement: string;
        id?: string | null;
      }[]
    | null;
  materials?:
    | {
        material: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  status?: ('draft' | 'published' | 'cancelled' | 'completed') | null;
  calendarColor?: ('blue' | 'purple' | 'green' | 'orange' | 'pink' | 'teal' | 'red') | null;
  /**
   * Define qué campos adicionales debe llenar el inscrito (nombre, apellido y email son obligatorios siempre)
   */
  registrationFields?:
    | {
        /**
         * Ej: "Carrera", "RUT", "Empresa"
         */
        fieldName: string;
        fieldType: 'text' | 'email' | 'tel' | 'number' | 'textarea' | 'select' | 'checkbox' | 'signature';
        required?: boolean | null;
        options?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Permitir inscripción desde la web (si está desactivado, usar URL externa)
   */
  enableDirectRegistration?: boolean | null;
  /**
   * El inscrito debe firmar digitalmente
   */
  requireSignature?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Inscripciones a eventos y talleres
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  fullName: string;
  lastName?: string | null;
  email: string;
  phone?: string | null;
  institution?: string | null;
  rut?: string | null;
  /**
   * Respuestas a los campos dinámicos definidos en el evento
   */
  customFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Firma del participante (base64)
   */
  signature?: string | null;
  status?: ('pending' | 'confirmed' | 'cancelled' | 'waitlist') | null;
  /**
   * Notas internas del administrador
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro de asistencia a eventos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-attendance".
 */
export interface EventAttendance {
  id: number;
  event: number | Event;
  registration: number | EventRegistration;
  attended?: boolean | null;
  checkInTime?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Documentos, guías y archivos descargables
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  /**
   * URL amigable (se genera automáticamente)
   */
  slug?: string | null;
  description?: string | null;
  type: 'document' | 'guide' | 'tutorial' | 'template' | 'software' | 'other';
  /**
   * PDF, ZIP, STL, o cualquier archivo descargable
   */
  file?: (number | null) | Media;
  /**
   * Si el recurso está alojado externamente (Google Drive, etc.)
   */
  externalUrl?: string | null;
  thumbnail?: (number | null) | Media;
  /**
   * Nombre de carpeta para organizar (ej: "Manuales", "Diseños 3D")
   */
  folder?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  visibility: 'public' | 'authenticated' | 'admin';
  downloads?: number | null;
  status?: ('draft' | 'published' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fotos y videos del FabLab
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  description?: string | null;
  image: number | Media;
  /**
   * Nombre del álbum para agrupar (ej: "Inauguración 2025", "Proyectos Destacados")
   */
  album?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  date?: string | null;
  featured?: boolean | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Preguntas frecuentes del FabLab
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'general' | 'membership' | 'services' | 'equipment' | 'events' | 'schedule' | 'payments';
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Testimonios de usuarios del FabLab
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  author: string;
  /**
   * Ej: "Estudiante de Ingeniería", "Emprendedor", "Profesor INACAP"
   */
  role?: string | null;
  content: string;
  avatar?: (number | null) | Media;
  /**
   * Del 1 al 5
   */
  rating?: number | null;
  /**
   * Opcional: vincular a un proyecto
   */
  projectLink?: (number | null) | Project;
  featured?: boolean | null;
  published?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  nombre: string;
  email: string;
  telefono?: string | null;
  asunto: string;
  mensaje: string;
  /**
   * Estado del mensaje de contacto
   */
  estado?: ('nuevo' | 'leido' | 'progreso' | 'resuelto') | null;
  /**
   * Respuesta enviada al usuario (solo para admin)
   */
  respuesta?: string | null;
  fechaRespuesta?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'blog-subscribers';
        value: number | BlogSubscriber;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'equipment';
        value: number | Equipment;
      } | null)
    | ({
        relationTo: 'equipment-requests';
        value: number | EquipmentRequest;
      } | null)
    | ({
        relationTo: 'equipment-usage';
        value: number | EquipmentUsage;
      } | null)
    | ({
        relationTo: 'inventory-items';
        value: number | InventoryItem;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'event-attendance';
        value: number | EventAttendance;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  imagePosition?: T;
  bio?: T;
  jobTitle?: T;
  showInTeam?: T;
  category?: T;
  experience?: T;
  educationStatus?: T;
  achievements?:
    | T
    | {
        achievement?: T;
        id?: T;
      };
  order?: T;
  linkedin?: T;
  github?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        techBox?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        gallery?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  author?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  views?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-subscribers_select".
 */
export interface BlogSubscribersSelect<T extends boolean = true> {
  email?: T;
  active?: T;
  unsubscribeToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  description?: T;
  content?: T;
  icon?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        item?: T;
        price?: T;
        notes?: T;
        id?: T;
      };
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  order?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment_select".
 */
export interface EquipmentSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  brand?: T;
  model?: T;
  description?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  materials?:
    | T
    | {
        material?: T;
        id?: T;
      };
  manuals?:
    | T
    | {
        title?: T;
        file?: T;
        url?: T;
        id?: T;
      };
  status?: T;
  location?: T;
  requiresTraining?: T;
  showInTecnologias?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-requests_select".
 */
export interface EquipmentRequestsSelect<T extends boolean = true> {
  equipmentName?: T;
  description?: T;
  quantity?: T;
  justification?: T;
  status?: T;
  requestedBy?: T;
  reviewedBy?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-usage_select".
 */
export interface EquipmentUsageSelect<T extends boolean = true> {
  equipmentId?: T;
  equipmentName?: T;
  user?: T;
  userName?: T;
  startTime?: T;
  endTime?: T;
  estimatedDuration?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-items_select".
 */
export interface InventoryItemsSelect<T extends boolean = true> {
  name?: T;
  sku?: T;
  category?: T;
  description?: T;
  image?: T;
  quantity?: T;
  unit?: T;
  minimumStock?: T;
  location?: T;
  supplier?: T;
  unitCost?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  category?: T;
  specialty?: T;
  image?: T;
  bio?: T;
  experience?: T;
  achievements?:
    | T
    | {
        achievement?: T;
        id?: T;
      };
  social?:
    | T
    | {
        email?: T;
        linkedin?: T;
        github?: T;
        twitter?: T;
      };
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  description?: T;
  content?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  creators?:
    | T
    | {
        teamMember?: T;
        externalName?: T;
        role?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  practiceHoursEnabled?: T;
  practiceHours?:
    | T
    | {
        beneficiaryType?: T;
        institutionName?: T;
        institutionRut?: T;
        email?: T;
        phone?: T;
        commune?: T;
        referringOrganization?: T;
        specialists?:
          | T
          | {
              firstName?: T;
              paternalLastName?: T;
              maternalLastName?: T;
              rut?: T;
              id?: T;
            };
        bidireccionEntries?:
          | T
          | {
              tipoBeneficiario?: T;
              rut?: T;
              firstName?: T;
              paternalLastName?: T;
              maternalLastName?: T;
              rol?: T;
              horasDocente?: T;
              horasEstudiante?: T;
              id?: T;
            };
      };
  year?: T;
  featured?: T;
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  description?: T;
  content?: T;
  featuredImage?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  isOnline?: T;
  instructor?: T;
  externalInstructor?: T;
  capacity?: T;
  registrationUrl?: T;
  price?: T;
  requirements?:
    | T
    | {
        requirement?: T;
        id?: T;
      };
  materials?:
    | T
    | {
        material?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  status?: T;
  calendarColor?: T;
  registrationFields?:
    | T
    | {
        fieldName?: T;
        fieldType?: T;
        required?: T;
        options?: T;
        id?: T;
      };
  enableDirectRegistration?: T;
  requireSignature?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  fullName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  institution?: T;
  rut?: T;
  customFields?: T;
  signature?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-attendance_select".
 */
export interface EventAttendanceSelect<T extends boolean = true> {
  event?: T;
  registration?: T;
  attended?: T;
  checkInTime?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  type?: T;
  file?: T;
  externalUrl?: T;
  thumbnail?: T;
  folder?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  visibility?: T;
  downloads?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  album?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  date?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  role?: T;
  content?: T;
  avatar?: T;
  rating?: T;
  projectLink?: T;
  featured?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  nombre?: T;
  email?: T;
  telefono?: T;
  asunto?: T;
  mensaje?: T;
  estado?: T;
  respuesta?: T;
  fechaRespuesta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Ajustes generales del sitio web
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Descripción para motores de búsqueda
   */
  siteDescription?: string | null;
  logo?: (number | null) | Media;
  /**
   * Versión clara para fondos oscuros
   */
  logoAlt?: (number | null) | Media;
  favicon?: (number | null) | Media;
  contactEmail?: string | null;
  contactPhone?: string | null;
  /**
   * Número con código de país (ej: +56912345678)
   */
  whatsapp?: string | null;
  address?: string | null;
  googleMapsUrl?: string | null;
  /**
   * Ej: "Lunes a Viernes: 9:00 - 18:00"
   */
  schedule?: string | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok' | 'github' | 'discord';
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ej: G-XXXXXXXXXX
   */
  googleAnalyticsId?: string | null;
  /**
   * Scripts que se insertarán en el <head>
   */
  customScripts?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configuración del contenido de la landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-config".
 */
export interface LandingConfig {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  ctaButtons?:
    | {
        text: string;
        url: string;
        variant?: ('primary' | 'secondary' | 'outline') | null;
        id?: string | null;
      }[]
    | null;
  showServices?: boolean | null;
  featuredServices?: (number | Service)[] | null;
  showProjects?: boolean | null;
  projectsCount?: number | null;
  showTeam?: boolean | null;
  showTestimonials?: boolean | null;
  showEvents?: boolean | null;
  upcomingEventsCount?: number | null;
  showStats?: boolean | null;
  stats?:
    | {
        /**
         * Ej: "500+", "1000", "50"
         */
        value: string;
        /**
         * Ej: "Proyectos", "Usuarios", "Cursos"
         */
        label: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipo-page".
 */
export interface EquipoPage {
  id: number;
  heroTitle?: string | null;
  heroDescription?: string | null;
  heroStats?:
    | {
        text: string;
        icon?: ('award' | 'users' | 'sparkles' | 'calendar' | 'rocket') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  logoAlt?: T;
  favicon?: T;
  contactEmail?: T;
  contactPhone?: T;
  whatsapp?: T;
  address?: T;
  googleMapsUrl?: T;
  schedule?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  googleAnalyticsId?: T;
  customScripts?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-config_select".
 */
export interface LandingConfigSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  ctaButtons?:
    | T
    | {
        text?: T;
        url?: T;
        variant?: T;
        id?: T;
      };
  showServices?: T;
  featuredServices?: T;
  showProjects?: T;
  projectsCount?: T;
  showTeam?: T;
  showTestimonials?: T;
  showEvents?: T;
  upcomingEventsCount?: T;
  showStats?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipo-page_select".
 */
export interface EquipoPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  heroStats?:
    | T
    | {
        text?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}